version: "3.8"
services:
  demo:
    image: chatbot
    hostname: chatbot
    build: .
    environment:
      - BACKEND_SERVICE=http://backend:9000
    ports:
      - 8080:7860
    extra_hosts:
      - "host.docker.internal:host-gateway"